<a href="https://colab.research.google.com/github/kratikasharma20/test1/blob/mainb1/RichiPCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
df = pd.read_csv("DNA_Data.csv")
df

    193913  297392  298062  383188  ...  244618  295985  244637  417226
0   0.3945  0.5016  0.1050  0.3408  ...  0.1765  0.1318  1.9860  2.0164
1   0.2986  0.3463  0.1067  0.4758  ...  0.3163  0.1825  1.6144  0.6081
2   0.2757  0.2993  0.1596  0.3620  ...  0.3363  0.1688  1.4510  0.4299
3   0.2607  3.3786  0.4292  0.9716  ...  0.4890  0.1914  2.4014  0.6155
4   0.4046  0.7828  0.2012  0.4327  ...  0.1979  0.1060  1.0644  0.5996
..     ...     ...     ...     ...  ...     ...     ...     ...     ...
83  0.4518  0.2413  0.1106  2.2634  ...  0.3062  2.1612  1.3119  0.3089
84  0.2495  0.1883  0.0617  3.0804  ...  0.6085  2.9724  1.5352  0.2060
85  0.2870  0.1721  0.0885  4.4771  ...  0.1534  1.1701  1.1367  0.2191
86  2.5600  3.1833  0.1397  0.3435  ...  0.0778  0.7321  0.4632  0.3071
87  0.4732  0.6712  0.1431  0.5069  ...  0.1394  0.0728  1.2876  0.5037

[88 rows x 59 columns]

In [ ]:
df.keys()

Index(['193913', '297392', '298062', '383188', '283315', '296448', '878280',
       '377461', '325182', '868304', '1469292', '1470048', '756401', '379708',
       '207274', '1435862', '461425', '357031', '769657', '812105', '47475',
       '767183', '241412', '810057', '183337', '839552', '786084', '785793',
       '796258', '486110', '489489', '1471841', '878652', '755145', '626502',
       '814526', '143306', '344134', '866702', '491565', '770059', '770394',
       '629896', '624360', '52076', '43733', '44563', '713922', '609663',
       '840942', '80109', '782811', '814260', '784224', '841641', '244618',
       '295985', '244637', '417226'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()
scaler.fit(df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaled_data=scaler.transform(df)

In [ ]:
scaled_data

array([[-0.35577224, -0.38980682, -0.38189299, ..., -0.87479476,
         1.21474341,  0.96873678],
       [-0.51513621, -0.53210604, -0.38110303, ..., -0.82308824,
         0.66376094, -0.38627495],
       [-0.5531908 , -0.57517149, -0.35652129, ..., -0.83706022,
         0.42148285, -0.55773209],
       ...,
       [-0.53441277, -0.69172307, -0.38956026, ...,  0.18411816,
        -0.04453919, -0.76055569],
       [ 3.24279581,  2.06739744, -0.36576848, ..., -0.26257727,
        -1.04315785, -0.6758855 ],
       [-0.22499076, -0.23440471, -0.36418856, ..., -0.93496606,
         0.17920477, -0.48672459]])

In [ ]:
pca=PCA(n_components=22)

In [ ]:
pca.fit(scaled_data)

PCA(copy=True, iterated_power='auto', n_components=22, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
x_pca=pca.transform(scaled_data)

In [ ]:
scaled_data.shape

(88, 59)

In [ ]:
x_pca.shape

(88, 22)

In [ ]:
scaled_data

array([[-0.35577224, -0.38980682, -0.38189299, ..., -0.87479476,
         1.21474341,  0.96873678],
       [-0.51513621, -0.53210604, -0.38110303, ..., -0.82308824,
         0.66376094, -0.38627495],
       [-0.5531908 , -0.57517149, -0.35652129, ..., -0.83706022,
         0.42148285, -0.55773209],
       ...,
       [-0.53441277, -0.69172307, -0.38956026, ...,  0.18411816,
        -0.04453919, -0.76055569],
       [ 3.24279581,  2.06739744, -0.36576848, ..., -0.26257727,
        -1.04315785, -0.6758855 ],
       [-0.22499076, -0.23440471, -0.36418856, ..., -0.93496606,
         0.17920477, -0.48672459]])

In [ ]:
x_pca

array([[-1.19440169e+00,  4.45356565e+00, -2.18025997e-01, ...,
        -7.65279027e-01, -1.57289699e-01, -5.44720264e-01],
       [-1.67609357e+00,  4.08213791e+00, -7.22182566e-01, ...,
         1.06282844e+00,  1.03462045e+00, -4.16234598e-01],
       [-2.02454862e+00,  4.59798655e+00,  2.65970964e-01, ...,
        -5.00592417e-01,  5.18915788e-01,  8.63348227e-01],
       ...,
       [-1.83019292e+00, -3.32727542e+00, -4.65505226e+00, ...,
        -8.02667382e-01,  8.07733497e-01,  5.41256691e-03],
       [ 1.07042329e+01, -3.05566398e-01,  1.04447710e-01, ...,
        -4.91673042e-01,  3.01873363e-02, -2.15475960e+00],
       [-2.57345716e+00,  5.37564566e+00, -1.29991591e-01, ...,
        -6.82377926e-01, -1.10058461e+00,  9.31574935e-01]])

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df1 = pd.DataFrame(x_pca)
df1

           0         1         2   ...        19        20        21
0   -1.194402  4.453566 -0.218026  ... -0.765279 -0.157290 -0.544720
1   -1.676094  4.082138 -0.722183  ...  1.062828  1.034620 -0.416235
2   -2.024549  4.597987  0.265971  ... -0.500592  0.518916  0.863348
3   -1.168589  2.901813 -0.504025  ...  0.913530  0.171464  0.404635
4   -1.045416  3.497829  0.405797  ...  0.107697  0.288441 -0.471235
..        ...       ...       ...  ...       ...       ...       ...
83  -0.738768 -2.615478 -3.000641  ... -0.075760  1.087298  0.076337
84  -1.361287 -3.405353 -4.259137  ...  0.047155  0.299265 -0.386701
85  -1.830193 -3.327275 -4.655052  ... -0.802667  0.807733  0.005413
86  10.704233 -0.305566  0.104448  ... -0.491673  0.030187 -2.154760
87  -2.573457  5.375646 -0.129992  ... -0.682378 -1.100585  0.931575

[88 rows x 22 columns]

In [ ]:
df1.keys()

RangeIndex(start=0, stop=22, step=1)

In [ ]:
df1.head()

         0         1         2   ...        19        20        21
0 -1.194402  4.453566 -0.218026  ... -0.765279 -0.157290 -0.544720
1 -1.676094  4.082138 -0.722183  ...  1.062828  1.034620 -0.416235
2 -2.024549  4.597987  0.265971  ... -0.500592  0.518916  0.863348
3 -1.168589  2.901813 -0.504025  ...  0.913530  0.171464  0.404635
4 -1.045416  3.497829  0.405797  ...  0.107697  0.288441 -0.471235

[5 rows x 22 columns]

In [ ]:
import pandas as pd

bins2 = pd.IntervalIndex.from_tuples(df1)

TypeError: ignored

In [ ]:
df1["pcaX_width"] = pd.cut(df1., bins=10)

SyntaxError: ignored